// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Timeboxed.Data;

#nullable disable

namespace Timeboxed.Data.Migrations
{
    [DbContext(typeof(TimeboxedContext))]
    [Migration("20221201022337_AddUserAccessControlTable")]
    partial class AddUserAccessControlTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Timeboxed.Domain.Models.Application", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<Guid>("AuditId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BackgroundImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BackgroundVideo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Colour")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Applications");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuditId = new Guid("00000000-0000-0000-0000-000000000000"),
                            BackgroundImage = "https://res.cloudinary.com/pmcglinchey/image/upload/v1656632136/smoulderedsignals_19201080_m0nwwf.png",
                            BackgroundVideo = "https://res.cloudinary.com/pmcglinchey/video/upload/v1656873263/smoulderingsignals_960540_looping_qu42se.mp4",
                            Colour = "#6d28d9",
                            Description = "A first class environment for managing rotas & employees in your business.",
                            Name = "Rota Manager",
                            Url = "/rotas/dashboard"
                        },
                        new
                        {
                            Id = 2,
                            AuditId = new Guid("00000000-0000-0000-0000-000000000000"),
                            BackgroundImage = "https://res.cloudinary.com/pmcglinchey/image/upload/v1656621688/electricwaves_19201080_ll3sa9.png",
                            BackgroundVideo = "https://res.cloudinary.com/pmcglinchey/video/upload/v1656873057/electricwaves_960540_looping_lczpjp.mp4",
                            Colour = "#e11d48",
                            Description = "A complete package for managing clients allowing you to spend more time where it really matters.",
                            Name = "Client Manager",
                            Url = "/clients/dashboard"
                        });
                });

            modelBuilder.Entity("Timeboxed.Domain.Models.ApplicationPermission", b =>
                {
                    b.Property<int>("ApplicationId")
                        .HasColumnType("int");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.HasKey("ApplicationId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("ApplicationPermissions");

                    b.HasData(
                        new
                        {
                            ApplicationId = 1,
                            PermissionId = 101
                        },
                        new
                        {
                            ApplicationId = 1,
                            PermissionId = 102
                        },
                        new
                        {
                            ApplicationId = 1,
                            PermissionId = 201
                        },
                        new
                        {
                            ApplicationId = 1,
                            PermissionId = 202
                        },
                        new
                        {
                            ApplicationId = 2,
                            PermissionId = 101
                        },
                        new
                        {
                            ApplicationId = 2,
                            PermissionId = 102
                        },
                        new
                        {
                            ApplicationId = 2,
                            PermissionId = 301
                        },
                        new
                        {
                            ApplicationId = 2,
                            PermissionId = 302
                        });
                });

            modelBuilder.Entity("Timeboxed.Domain.Models.Audit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Audits");
                });

            modelBuilder.Entity("Timeboxed.Domain.Models.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Colour")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstLine")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleNames")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrimaryEmailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrimaryPhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecondLine")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThirdLine")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ZipCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("Timeboxed.Domain.Models.Common.Email", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Emails");
                });

            modelBuilder.Entity("Timeboxed.Domain.Models.Common.PhoneNumber", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("PhoneNumbers");
                });

            modelBuilder.Entity("Timeboxed.Domain.Models.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Colour")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstLine")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("LinkedUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("MaxHours")
                        .HasColumnType("int");

                    b.Property<string>("MiddleNames")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MinHours")
                        .HasColumnType("int");

                    b.Property<string>("PostCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrimaryEmailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrimaryPhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ReportsToId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("Role")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SecondLine")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("ThirdLine")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ZipCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("LinkedUserId");

                    b.HasIndex("ReportsToId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("Timeboxed.Domain.Models.EmployeeHoliday", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("date");

                    b.Property<bool?>("IsPaid")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("EmployeeHolidays");
                });

            modelBuilder.Entity("Timeboxed.Domain.Models.EmployeePreferences", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("MaxHours")
                        .HasColumnType("int");

                    b.Property<int?>("MinHours")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("EmployeePreferences");
                });

            modelBuilder.Entity("Timeboxed.Domain.Models.EmployeeSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ScheduleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ScheduleId");

                    b.ToTable("EmployeeSchedules");
                });

            modelBuilder.Entity("Timeboxed.Domain.Models.EmployeeScheduleShift", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<Guid?>("EmployeeScheduleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EndHour")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StartHour")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeScheduleId");

                    b.ToTable("EmployeeScheduleShifts");
                });

            modelBuilder.Entity("Timeboxed.Domain.Models.EmployeeUnavailableDays", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<Guid?>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EmployeePreferencesId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("EmployeePreferencesId");

                    b.ToTable("EmployeeUnavailableDays");
                });

            modelBuilder.Entity("Timeboxed.Domain.Models.Group", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Colour")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("Timeboxed.Domain.Models.GroupApplication", b =>
                {
                    b.Property<int>("ApplicationId")
                        .HasColumnType("int");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ApplicationId", "GroupId");

                    b.HasIndex("GroupId");

                    b.ToTable("GroupApplications");
                });

            modelBuilder.Entity("Timeboxed.Domain.Models.GroupClientTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("GroupClientTags");
                });

            modelBuilder.Entity("Timeboxed.Domain.Models.GroupUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("HasJoined")
                        .HasColumnType("bit");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("UserId");

                    b.ToTable("GroupUsers");
                });

            modelBuilder.Entity("Timeboxed.Domain.Models.GroupUserApplication", b =>
                {
                    b.Property<int>("ApplicationId")
                        .HasColumnType("int");

                    b.Property<Guid>("GroupUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ApplicationId", "GroupUserId");

                    b.HasIndex("GroupUserId");

                    b.ToTable("GroupUserApplications");
                });

            modelBuilder.Entity("Timeboxed.Domain.Models.GroupUserRole", b =>
                {
                    b.Property<Guid>("GroupUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("GroupUserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("GroupUserRoles");
                });

            modelBuilder.Entity("Timeboxed.Domain.Models.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<Guid>("AuditId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuditId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Description = "Grants access to a group.",
                            Language = "en-US",
                            Name = "Group Access"
                        },
                        new
                        {
                            Id = 2,
                            AuditId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Description = "Grants admin access to a group.",
                            Language = "en-US",
                            Name = "Group Admin Access"
                        },
                        new
                        {
                            Id = 101,
                            AuditId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Description = "Grants access to an application.",
                            Language = "en-US",
                            Name = "Application Access"
                        },
                        new
                        {
                            Id = 102,
                            AuditId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Description = "Grants admin access to an application.",
                            Language = "en-US",
                            Name = "Application Admin"
                        },
                        new
                        {
                            Id = 201,
                            AuditId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Description = "Grants view access to rotas in the group.",
                            Language = "en-US",
                            Name = "View Rotas"
                        },
                        new
                        {
                            Id = 202,
                            AuditId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Description = "Grants add, edit & delete access to rotas in a group.",
                            Language = "en-US",
                            Name = "Add, Edit & Delete Rotas"
                        },
                        new
                        {
                            Id = 301,
                            AuditId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Description = "Grants view access to clients in a group.",
                            Language = "en-US",
                            Name = "View Clients"
                        },
                        new
                        {
                            Id = 302,
                            AuditId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Description = "Grants add, edit & delete access to clients in a group",
                            Language = "en-US",
                            Name = "Add, Edit & Delete Clients"
                        });
                });

            modelBuilder.Entity("Timeboxed.Domain.Models.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("ApplicationId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.HasIndex("GroupId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1ba0c5a2-00a5-4b37-9e97-cc354ad6d9e2"),
                            Description = "Intended to be assigned to highest level group members.",
                            Name = "Group Admin"
                        },
                        new
                        {
                            Id = new Guid("39a759e0-4991-498f-8612-4e2fc709a9b2"),
                            Description = "Intended to be assigned to base level group members.",
                            Name = "Group Member"
                        },
                        new
                        {
                            Id = new Guid("24cda806-3a28-45f8-9f6d-d64a613385cb"),
                            ApplicationId = 1,
                            Description = "Intended to be assigned to base level rota manager users.",
                            Name = "Rota Manager User"
                        },
                        new
                        {
                            Id = new Guid("78114707-a61a-46e7-9914-f918de3f89fa"),
                            ApplicationId = 1,
                            Description = "Intended to be assigned to highest level rota manager users.",
                            Name = "Rota Manager Admin"
                        },
                        new
                        {
                            Id = new Guid("16befbf9-1ade-4fad-b0ed-0080f82e8230"),
                            ApplicationId = 2,
                            Description = "Intended to be assigned to base level client manager users.",
                            Name = "Client Manager User"
                        },
                        new
                        {
                            Id = new Guid("dcd622b3-400c-45e2-9451-23af77b7f835"),
                            ApplicationId = 2,
                            Description = "Intended to be assigned to highest level client manager users.",
                            Name = "Client Manager Admin"
                        });
                });

            modelBuilder.Entity("Timeboxed.Domain.Models.RolePermission", b =>
                {
                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PermissionId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("RolePermissions");

                    b.HasData(
                        new
                        {
                            PermissionId = 1,
                            RoleId = new Guid("1ba0c5a2-00a5-4b37-9e97-cc354ad6d9e2")
                        },
                        new
                        {
                            PermissionId = 2,
                            RoleId = new Guid("1ba0c5a2-00a5-4b37-9e97-cc354ad6d9e2")
                        },
                        new
                        {
                            PermissionId = 1,
                            RoleId = new Guid("39a759e0-4991-498f-8612-4e2fc709a9b2")
                        },
                        new
                        {
                            PermissionId = 101,
                            RoleId = new Guid("24cda806-3a28-45f8-9f6d-d64a613385cb")
                        },
                        new
                        {
                            PermissionId = 201,
                            RoleId = new Guid("24cda806-3a28-45f8-9f6d-d64a613385cb")
                        },
                        new
                        {
                            PermissionId = 101,
                            RoleId = new Guid("78114707-a61a-46e7-9914-f918de3f89fa")
                        },
                        new
                        {
                            PermissionId = 201,
                            RoleId = new Guid("78114707-a61a-46e7-9914-f918de3f89fa")
                        },
                        new
                        {
                            PermissionId = 202,
                            RoleId = new Guid("78114707-a61a-46e7-9914-f918de3f89fa")
                        },
                        new
                        {
                            PermissionId = 101,
                            RoleId = new Guid("16befbf9-1ade-4fad-b0ed-0080f82e8230")
                        },
                        new
                        {
                            PermissionId = 301,
                            RoleId = new Guid("16befbf9-1ade-4fad-b0ed-0080f82e8230")
                        },
                        new
                        {
                            PermissionId = 101,
                            RoleId = new Guid("dcd622b3-400c-45e2-9451-23af77b7f835")
                        },
                        new
                        {
                            PermissionId = 301,
                            RoleId = new Guid("dcd622b3-400c-45e2-9451-23af77b7f835")
                        },
                        new
                        {
                            PermissionId = 302,
                            RoleId = new Guid("dcd622b3-400c-45e2-9451-23af77b7f835")
                        });
                });

            modelBuilder.Entity("Timeboxed.Domain.Models.Rota", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("ClosingHour")
                        .HasColumnType("int");

                    b.Property<string>("Colour")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("Locked")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("Rotas");
                });

            modelBuilder.Entity("Timeboxed.Domain.Models.RotaEmployee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RotaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("RotaId");

                    b.ToTable("RotaEmployees");
                });

            modelBuilder.Entity("Timeboxed.Domain.Models.Schedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Locked")
                        .HasColumnType("bit");

                    b.Property<Guid>("RotaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("RotaId");

                    b.ToTable("Schedules");
                });

            modelBuilder.Entity("Timeboxed.Domain.Models.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SessionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("Timeboxed.Domain.Models.SessionTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GroupClientTagId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("GroupClientTagId");

                    b.HasIndex("SessionId");

                    b.ToTable("SessionTags");
                });

            modelBuilder.Entity("Timeboxed.Domain.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Timeboxed.Domain.Models.UserAccessControl", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AlphaAccessKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserAccessControl");
                });

            modelBuilder.Entity("Timeboxed.Domain.Models.UserPreferences", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DefaultGroup")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserPreferences");
                });

            modelBuilder.Entity("Timeboxed.Domain.Models.ApplicationPermission", b =>
                {
                    b.HasOne("Timeboxed.Domain.Models.Application", null)
                        .WithMany()
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Timeboxed.Domain.Models.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Timeboxed.Domain.Models.Client", b =>
                {
                    b.HasOne("Timeboxed.Domain.Models.Group", "Group")
                        .WithMany("Clients")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("Timeboxed.Domain.Models.Common.Email", b =>
                {
                    b.HasOne("Timeboxed.Domain.Models.Client", null)
                        .WithMany("Emails")
                        .HasForeignKey("ClientId");

                    b.HasOne("Timeboxed.Domain.Models.Employee", null)
                        .WithMany("Emails")
                        .HasForeignKey("EmployeeId");
                });

            modelBuilder.Entity("Timeboxed.Domain.Models.Common.PhoneNumber", b =>
                {
                    b.HasOne("Timeboxed.Domain.Models.Client", null)
                        .WithMany("PhoneNumbers")
                        .HasForeignKey("ClientId");

                    b.HasOne("Timeboxed.Domain.Models.Employee", null)
                        .WithMany("PhoneNumbers")
                        .HasForeignKey("EmployeeId");
                });

            modelBuilder.Entity("Timeboxed.Domain.Models.Employee", b =>
                {
                    b.HasOne("Timeboxed.Domain.Models.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Timeboxed.Domain.Models.User", "LinkedUser")
                        .WithMany()
                        .HasForeignKey("LinkedUserId");

                    b.HasOne("Timeboxed.Domain.Models.Employee", "ReportsTo")
                        .WithMany()
                        .HasForeignKey("ReportsToId");

                    b.Navigation("Group");

                    b.Navigation("LinkedUser");

                    b.Navigation("ReportsTo");
                });

            modelBuilder.Entity("Timeboxed.Domain.Models.EmployeeHoliday", b =>
                {
                    b.HasOne("Timeboxed.Domain.Models.Employee", null)
                        .WithMany("Holidays")
                        .HasForeignKey("EmployeeId");
                });

            modelBuilder.Entity("Timeboxed.Domain.Models.EmployeeSchedule", b =>
                {
                    b.HasOne("Timeboxed.Domain.Models.Schedule", null)
                        .WithMany("EmployeeSchedules")
                        .HasForeignKey("ScheduleId");
                });

            modelBuilder.Entity("Timeboxed.Domain.Models.EmployeeScheduleShift", b =>
                {
                    b.HasOne("Timeboxed.Domain.Models.EmployeeSchedule", null)
                        .WithMany("Shifts")
                        .HasForeignKey("EmployeeScheduleId");
                });

            modelBuilder.Entity("Timeboxed.Domain.Models.EmployeeUnavailableDays", b =>
                {
                    b.HasOne("Timeboxed.Domain.Models.Employee", null)
                        .WithMany("UnavailableDays")
                        .HasForeignKey("EmployeeId");

                    b.HasOne("Timeboxed.Domain.Models.EmployeePreferences", "EmployeePreferences")
                        .WithMany("UnavailableDays")
                        .HasForeignKey("EmployeePreferencesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmployeePreferences");
                });

            modelBuilder.Entity("Timeboxed.Domain.Models.GroupApplication", b =>
                {
                    b.HasOne("Timeboxed.Domain.Models.Application", null)
                        .WithMany()
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Timeboxed.Domain.Models.Group", null)
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Timeboxed.Domain.Models.GroupClientTag", b =>
                {
                    b.HasOne("Timeboxed.Domain.Models.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("Timeboxed.Domain.Models.GroupUser", b =>
                {
                    b.HasOne("Timeboxed.Domain.Models.Group", "Group")
                        .WithMany("GroupUsers")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Timeboxed.Domain.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Timeboxed.Domain.Models.GroupUserApplication", b =>
                {
                    b.HasOne("Timeboxed.Domain.Models.Application", null)
                        .WithMany()
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Timeboxed.Domain.Models.GroupUser", null)
                        .WithMany()
                        .HasForeignKey("GroupUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Timeboxed.Domain.Models.GroupUserRole", b =>
                {
                    b.HasOne("Timeboxed.Domain.Models.GroupUser", null)
                        .WithMany()
                        .HasForeignKey("GroupUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Timeboxed.Domain.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Timeboxed.Domain.Models.Role", b =>
                {
                    b.HasOne("Timeboxed.Domain.Models.Application", "Application")
                        .WithMany()
                        .HasForeignKey("ApplicationId");

                    b.HasOne("Timeboxed.Domain.Models.Group", "Group")
                        .WithMany("Roles")
                        .HasForeignKey("GroupId");

                    b.Navigation("Application");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("Timeboxed.Domain.Models.RolePermission", b =>
                {
                    b.HasOne("Timeboxed.Domain.Models.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Timeboxed.Domain.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Timeboxed.Domain.Models.Rota", b =>
                {
                    b.HasOne("Timeboxed.Domain.Models.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("Timeboxed.Domain.Models.RotaEmployee", b =>
                {
                    b.HasOne("Timeboxed.Domain.Models.Employee", "Employee")
                        .WithMany("Rotas")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("Timeboxed.Domain.Models.Rota", "Rota")
                        .WithMany("Employees")
                        .HasForeignKey("RotaId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Rota");
                });

            modelBuilder.Entity("Timeboxed.Domain.Models.Schedule", b =>
                {
                    b.HasOne("Timeboxed.Domain.Models.Rota", "Rota")
                        .WithMany("Schedules")
                        .HasForeignKey("RotaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rota");
                });

            modelBuilder.Entity("Timeboxed.Domain.Models.Session", b =>
                {
                    b.HasOne("Timeboxed.Domain.Models.Client", "Client")
                        .WithMany("Sessions")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Timeboxed.Domain.Models.SessionTag", b =>
                {
                    b.HasOne("Timeboxed.Domain.Models.GroupClientTag", "GroupClientTag")
                        .WithMany("Tags")
                        .HasForeignKey("GroupClientTagId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Timeboxed.Domain.Models.Session", "Session")
                        .WithMany("Tags")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GroupClientTag");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Timeboxed.Domain.Models.UserPreferences", b =>
                {
                    b.HasOne("Timeboxed.Domain.Models.User", null)
                        .WithOne("Preferences")
                        .HasForeignKey("Timeboxed.Domain.Models.UserPreferences", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Timeboxed.Domain.Models.Client", b =>
                {
                    b.Navigation("Emails");

                    b.Navigation("PhoneNumbers");

                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("Timeboxed.Domain.Models.Employee", b =>
                {
                    b.Navigation("Emails");

                    b.Navigation("Holidays");

                    b.Navigation("PhoneNumbers");

                    b.Navigation("Rotas");

                    b.Navigation("UnavailableDays");
                });

            modelBuilder.Entity("Timeboxed.Domain.Models.EmployeePreferences", b =>
                {
                    b.Navigation("UnavailableDays");
                });

            modelBuilder.Entity("Timeboxed.Domain.Models.EmployeeSchedule", b =>
                {
                    b.Navigation("Shifts");
                });

            modelBuilder.Entity("Timeboxed.Domain.Models.Group", b =>
                {
                    b.Navigation("Clients");

                    b.Navigation("GroupUsers");

                    b.Navigation("Roles");
                });

            modelBuilder.Entity("Timeboxed.Domain.Models.GroupClientTag", b =>
                {
                    b.Navigation("Tags");
                });

            modelBuilder.Entity("Timeboxed.Domain.Models.Rota", b =>
                {
                    b.Navigation("Employees");

                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("Timeboxed.Domain.Models.Schedule", b =>
                {
                    b.Navigation("EmployeeSchedules");
                });

            modelBuilder.Entity("Timeboxed.Domain.Models.Session", b =>
                {
                    b.Navigation("Tags");
                });

            modelBuilder.Entity("Timeboxed.Domain.Models.User", b =>
                {
                    b.Navigation("Preferences");
                });
#pragma warning restore 612, 618
        }
    }
}
